name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ✅ Step 3: Install dependencies
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk wget
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      # ✅ Step 4: Install Android SDK manually
      - name: Install Android SDK and accept licenses
        run: |
          # Setup paths
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          # Download and extract cmdline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/

          # Accept all licenses
          yes | sdkmanager --licenses

          # Install SDK components
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;36.1.0"

      # ✅ Step 5: Set environment variables for Buildozer
      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      # ✅ Step 6: Build APK with Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # ✅ Step 7: Upload the generated APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk